[2020-06-24 19:11:42,790] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: integrator.task_id_1 2020-06-20T00:00:00+00:00 [queued]>
[2020-06-24 19:11:42,815] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: integrator.task_id_1 2020-06-20T00:00:00+00:00 [queued]>
[2020-06-24 19:11:42,815] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-24 19:11:42,815] {taskinstance.py:880} INFO - Starting attempt 2 of 2
[2020-06-24 19:11:42,815] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-24 19:11:42,840] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): task_id_1> on 2020-06-20T00:00:00+00:00
[2020-06-24 19:11:42,843] {standard_task_runner.py:53} INFO - Started process 14152 to run task
[2020-06-24 19:11:42,929] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: integrator.task_id_1 2020-06-20T00:00:00+00:00 [running]> strx
[2020-06-24 19:11:42,955] {logging_mixin.py:112} INFO - hello
[2020-06-24 19:11:42,972] {taskinstance.py:1145} ERROR - The conn_id `mongodb://localhost:27017/cmpc` isn't defined
Traceback (most recent call last):
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/isaias/airflow/dags/integrator.py", line 108, in HelloDBOperator
    hook = MongoHook(conn_id=mongo_conn_id)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/contrib/hooks/mongo_hook.py", line 44, in __init__
    self.connection = self.get_connection(conn_id)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/hooks/base_hook.py", line 84, in get_connection
    conn = random.choice(list(cls.get_connections(conn_id)))
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/hooks/base_hook.py", line 80, in get_connections
    return secrets.get_connections(conn_id)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/secrets/__init__.py", line 56, in get_connections
    raise AirflowException("The conn_id `{0}` isn't defined".format(conn_id))
airflow.exceptions.AirflowException: The conn_id `mongodb://localhost:27017/cmpc` isn't defined
[2020-06-24 19:11:42,974] {taskinstance.py:1187} INFO - All retries failed; marking task as FAILED.dag_id=integrator, task_id=task_id_1, execution_date=20200620T000000, start_date=20200624T231142, end_date=20200624T231142
[2020-06-24 19:11:52,777] {logging_mixin.py:112} INFO - [2020-06-24 19:11:52,776] {local_task_job.py:103} INFO - Task exited with return code 1
