[2020-06-09 17:14:28,222] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: generator.generate_file 2020-06-09T21:13:54.763045+00:00 [queued]>
[2020-06-09 17:14:28,248] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: generator.generate_file 2020-06-09T21:13:54.763045+00:00 [queued]>
[2020-06-09 17:14:28,248] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-09 17:14:28,248] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-09 17:14:28,248] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-09 17:14:28,507] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): generate_file> on 2020-06-09T21:13:54.763045+00:00
[2020-06-09 17:14:28,509] {standard_task_runner.py:53} INFO - Started process 21746 to run task
[2020-06-09 17:14:28,674] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: generator.generate_file 2020-06-09T21:13:54.763045+00:00 [running]> strx
[2020-06-09 17:14:28,682] {logging_mixin.py:112} INFO - Generating  1591737268 ...
[2020-06-09 17:14:28,682] {taskinstance.py:1145} ERROR - [Errno 2] No such file or directory: '../../cmpc_data/descortezador_1591737268.csv'
Traceback (most recent call last):
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/isaias/airflow/dags/generator.py", line 60, in generate_file
    with open(filepath , 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../cmpc_data/descortezador_1591737268.csv'
[2020-06-09 17:14:28,704] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-09 17:14:38,027] {logging_mixin.py:112} INFO - [2020-06-09 17:14:38,026] {local_task_job.py:103} INFO - Task exited with return code 1
