[2020-06-24 19:07:59,710] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: integrator.task_id_1 2020-06-23T16:00:00+00:00 [queued]>
[2020-06-24 19:07:59,763] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: integrator.task_id_1 2020-06-23T16:00:00+00:00 [queued]>
[2020-06-24 19:07:59,764] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-24 19:07:59,764] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-24 19:07:59,765] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-24 19:07:59,808] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): task_id_1> on 2020-06-23T16:00:00+00:00
[2020-06-24 19:07:59,812] {standard_task_runner.py:53} INFO - Started process 9305 to run task
[2020-06-24 19:08:00,080] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: integrator.task_id_1 2020-06-23T16:00:00+00:00 [running]> strx
[2020-06-24 19:08:00,192] {logging_mixin.py:112} INFO - hello
[2020-06-24 19:08:00,245] {taskinstance.py:1145} ERROR - The conn_id `mongodb://localhost:27017` isn't defined
Traceback (most recent call last):
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/isaias/airflow/dags/integrator.py", line 108, in HelloDBOperator
    hook = MongoHook(conn_id=mongo_conn_id)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/contrib/hooks/mongo_hook.py", line 44, in __init__
    self.connection = self.get_connection(conn_id)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/hooks/base_hook.py", line 84, in get_connection
    conn = random.choice(list(cls.get_connections(conn_id)))
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/hooks/base_hook.py", line 80, in get_connections
    return secrets.get_connections(conn_id)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/secrets/__init__.py", line 56, in get_connections
    raise AirflowException("The conn_id `{0}` isn't defined".format(conn_id))
airflow.exceptions.AirflowException: The conn_id `mongodb://localhost:27017` isn't defined
[2020-06-24 19:08:00,251] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-24 19:08:09,576] {logging_mixin.py:112} INFO - [2020-06-24 19:08:09,576] {local_task_job.py:103} INFO - Task exited with return code 1
