[2020-06-17 19:05:29,822] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: MIS_v1.save_raw 2020-06-17T23:05:05+00:00 [queued]>
[2020-06-17 19:05:29,833] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: MIS_v1.save_raw 2020-06-17T23:05:05+00:00 [queued]>
[2020-06-17 19:05:29,833] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-17 19:05:29,833] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-17 19:05:29,833] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-17 19:05:30,002] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): save_raw> on 2020-06-17T23:05:05+00:00
[2020-06-17 19:05:30,004] {standard_task_runner.py:53} INFO - Started process 5674 to run task
[2020-06-17 19:05:30,203] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: MIS_v1.save_raw 2020-06-17T23:05:05+00:00 [running]> strx
[2020-06-17 19:05:30,212] {logging_mixin.py:112} INFO - Saving raw...
[2020-06-17 19:05:30,212] {taskinstance.py:1145} ERROR - expected str, bytes or os.PathLike object, not PythonOperator
Traceback (most recent call last):
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/isaias/airflow/dags/extract_MIS.py", line 124, in save_raw
    copy_raw(filepath,RAW_FOLDER+SYSTEM_FOLDER)
  File "/home/isaias/airflow/dags/extract_MIS.py", line 86, in copy_raw
    filename = os.path.basename(from_)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not PythonOperator
[2020-06-17 19:05:30,246] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-17 19:05:39,694] {logging_mixin.py:112} INFO - [2020-06-17 19:05:39,693] {local_task_job.py:103} INFO - Task exited with return code 1
