[2020-06-17 19:10:36,055] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: MIS_v1.save_raw 2020-06-17T23:05:05+00:00 [queued]>
[2020-06-17 19:10:36,066] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: MIS_v1.save_raw 2020-06-17T23:05:05+00:00 [queued]>
[2020-06-17 19:10:36,066] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-17 19:10:36,067] {taskinstance.py:880} INFO - Starting attempt 2 of 2
[2020-06-17 19:10:36,067] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-17 19:10:36,266] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): save_raw> on 2020-06-17T23:05:05+00:00
[2020-06-17 19:10:36,270] {standard_task_runner.py:53} INFO - Started process 6638 to run task
[2020-06-17 19:10:36,467] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: MIS_v1.save_raw 2020-06-17T23:05:05+00:00 [running]> strx
[2020-06-17 19:10:36,481] {logging_mixin.py:112} INFO - Saving raw...
[2020-06-17 19:10:36,481] {taskinstance.py:1145} ERROR - expected str, bytes or os.PathLike object, not PythonOperator
Traceback (most recent call last):
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/isaias/airflow/dags/extract_MIS.py", line 124, in save_raw
    copy_raw(filepath,RAW_FOLDER+SYSTEM_FOLDER)
  File "/home/isaias/airflow/dags/extract_MIS.py", line 86, in copy_raw
    filename = os.path.basename(from_)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not PythonOperator
[2020-06-17 19:10:36,483] {taskinstance.py:1187} INFO - All retries failed; marking task as FAILED.dag_id=MIS_v1, task_id=save_raw, execution_date=20200617T230505, start_date=20200617T231036, end_date=20200617T231036
[2020-06-17 19:10:45,914] {logging_mixin.py:112} INFO - [2020-06-17 19:10:45,913] {local_task_job.py:103} INFO - Task exited with return code 1
