[2020-06-17 19:38:04,493] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: MIS_v3.mis_sensor 2020-06-17T23:37:55.738922+00:00 [queued]>
[2020-06-17 19:38:04,507] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: MIS_v3.mis_sensor 2020-06-17T23:37:55.738922+00:00 [queued]>
[2020-06-17 19:38:04,507] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-17 19:38:04,507] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-17 19:38:04,507] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-17 19:38:04,950] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): mis_sensor> on 2020-06-17T23:37:55.738922+00:00
[2020-06-17 19:38:04,953] {standard_task_runner.py:53} INFO - Started process 10335 to run task
[2020-06-17 19:38:05,168] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: MIS_v3.mis_sensor 2020-06-17T23:37:55.738922+00:00 [running]> strx
[2020-06-17 19:38:05,179] {logging_mixin.py:112} INFO - Sensoring...
[2020-06-17 19:41:05,794] {logging_mixin.py:112} INFO - [2020-06-17 19:41:05,792] {local_task_job.py:167} WARNING - State of this instance has been externally set to None. Taking the poison pill.
[2020-06-17 19:41:05,804] {helpers.py:325} INFO - Sending Signals.SIGTERM to GPID 10335
[2020-06-17 19:41:05,804] {taskinstance.py:954} ERROR - Received SIGTERM. Terminating subprocesses.
[2020-06-17 19:41:05,808] {taskinstance.py:1145} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/isaias/airflow/dags/extract_MIS.py", line 111, in mis_sensor
    sleep(5)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 956, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2020-06-17 19:41:05,810] {taskinstance.py:1187} INFO - All retries failed; marking task as FAILED.dag_id=MIS_v3, task_id=mis_sensor, execution_date=20200617T233755, start_date=20200617T233804, end_date=20200617T234105
[2020-06-17 19:41:06,057] {helpers.py:291} INFO - Process psutil.Process(pid=10335, status='terminated') (10335) terminated with exit code 1
[2020-06-17 19:41:10,793] {logging_mixin.py:112} INFO - [2020-06-17 19:41:10,793] {local_task_job.py:103} INFO - Task exited with return code 1
