[2020-06-18 22:13:51,044] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: sap.sensor 2020-06-19T02:13:44.683818+00:00 [queued]>
[2020-06-18 22:13:51,087] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: sap.sensor 2020-06-19T02:13:44.683818+00:00 [queued]>
[2020-06-18 22:13:51,087] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 22:13:51,088] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-18 22:13:51,088] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 22:13:51,124] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): sensor> on 2020-06-19T02:13:44.683818+00:00
[2020-06-18 22:13:51,129] {standard_task_runner.py:53} INFO - Started process 29069 to run task
[2020-06-18 22:13:51,253] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: sap.sensor 2020-06-19T02:13:44.683818+00:00 [running]> strx
[2020-06-18 22:13:51,292] {logging_mixin.py:112} INFO - Sensoring...
[2020-06-18 22:17:09,223] {logging_mixin.py:112} INFO - [2020-06-18 22:17:09,222] {local_task_job.py:167} WARNING - State of this instance has been externally set to None. Taking the poison pill.
[2020-06-18 22:17:09,241] {helpers.py:325} INFO - Sending Signals.SIGTERM to GPID 29069
[2020-06-18 22:17:09,241] {taskinstance.py:954} ERROR - Received SIGTERM. Terminating subprocesses.
[2020-06-18 22:17:09,256] {taskinstance.py:1145} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/isaias/airflow/dags/extract_SAP.py", line 112, in sensor
    sleep(5)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 956, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2020-06-18 22:17:09,269] {taskinstance.py:1187} INFO - All retries failed; marking task as FAILED.dag_id=sap, task_id=sensor, execution_date=20200619T021344, start_date=20200619T021351, end_date=20200619T021709
[2020-06-18 22:17:09,355] {helpers.py:291} INFO - Process psutil.Process(pid=29069, status='terminated') (29069) terminated with exit code 1
[2020-06-18 22:17:14,196] {logging_mixin.py:112} INFO - [2020-06-18 22:17:14,195] {local_task_job.py:103} INFO - Task exited with return code 1
