[2020-06-18 22:13:08,869] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: sh_macerado.sensor 2020-06-19T02:13:01.547759+00:00 [queued]>
[2020-06-18 22:13:08,923] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: sh_macerado.sensor 2020-06-19T02:13:01.547759+00:00 [queued]>
[2020-06-18 22:13:08,939] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 22:13:08,939] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-18 22:13:08,939] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 22:13:08,974] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): sensor> on 2020-06-19T02:13:01.547759+00:00
[2020-06-18 22:13:08,980] {standard_task_runner.py:53} INFO - Started process 28259 to run task
[2020-06-18 22:13:09,219] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: sh_macerado.sensor 2020-06-19T02:13:01.547759+00:00 [running]> strx
[2020-06-18 22:13:09,262] {logging_mixin.py:112} INFO - Sensoring...
[2020-06-18 22:17:04,225] {logging_mixin.py:112} INFO - [2020-06-18 22:17:04,222] {local_task_job.py:167} WARNING - State of this instance has been externally set to None. Taking the poison pill.
[2020-06-18 22:17:04,251] {helpers.py:325} INFO - Sending Signals.SIGTERM to GPID 28259
[2020-06-18 22:17:04,252] {taskinstance.py:954} ERROR - Received SIGTERM. Terminating subprocesses.
[2020-06-18 22:17:04,266] {taskinstance.py:1145} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/isaias/airflow/dags/extract_SH_macerado.py", line 112, in sensor
    sleep(5)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 956, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2020-06-18 22:17:04,269] {taskinstance.py:1187} INFO - All retries failed; marking task as FAILED.dag_id=sh_macerado, task_id=sensor, execution_date=20200619T021301, start_date=20200619T021308, end_date=20200619T021704
[2020-06-18 22:17:04,353] {helpers.py:291} INFO - Process psutil.Process(pid=28259, status='terminated') (28259) terminated with exit code 1
[2020-06-18 22:17:09,196] {logging_mixin.py:112} INFO - [2020-06-18 22:17:09,196] {local_task_job.py:103} INFO - Task exited with return code 1
