[2020-06-18 09:34:28,255] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: MIS_v6.save_raw 2020-06-18T13:32:41.350629+00:00 [queued]>
[2020-06-18 09:34:28,264] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: MIS_v6.save_raw 2020-06-18T13:32:41.350629+00:00 [queued]>
[2020-06-18 09:34:28,264] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 09:34:28,264] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-18 09:34:28,264] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 09:34:28,427] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): save_raw> on 2020-06-18T13:32:41.350629+00:00
[2020-06-18 09:34:28,431] {standard_task_runner.py:53} INFO - Started process 12986 to run task
[2020-06-18 09:34:28,635] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: MIS_v6.save_raw 2020-06-18T13:32:41.350629+00:00 [running]> strx
[2020-06-18 09:34:28,643] {logging_mixin.py:112} INFO - Saving raw...
[2020-06-18 09:34:28,646] {taskinstance.py:1145} ERROR - [Errno 2] No such file or directory: '/home/isaias/cmpc_data/MIS/plywood2 (3rd copy).xlsx'
Traceback (most recent call last):
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/isaias/airflow/dags/extract_MIS.py", line 126, in save_raw
    copy_raw(filepath,RAW_FOLDER+SYSTEM_FOLDER)
  File "/home/isaias/airflow/dags/extract_MIS.py", line 87, in copy_raw
    shutil.copyfile(from_, to_+filename)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/isaias/cmpc_data/MIS/plywood2 (3rd copy).xlsx'
[2020-06-18 09:34:28,667] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-18 09:34:38,097] {logging_mixin.py:112} INFO - [2020-06-18 09:34:38,096] {local_task_job.py:103} INFO - Task exited with return code 1
