[2020-06-18 11:39:13,820] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: sh_macerado_v2.save_raw 2020-06-18T15:38:42.811697+00:00 [queued]>
[2020-06-18 11:39:13,841] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: sh_macerado_v2.save_raw 2020-06-18T15:38:42.811697+00:00 [queued]>
[2020-06-18 11:39:13,841] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 11:39:13,841] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-18 11:39:13,841] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-18 11:39:14,042] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): save_raw> on 2020-06-18T15:38:42.811697+00:00
[2020-06-18 11:39:14,045] {standard_task_runner.py:53} INFO - Started process 22834 to run task
[2020-06-18 11:39:14,258] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: sh_macerado_v2.save_raw 2020-06-18T15:38:42.811697+00:00 [running]> strx
[2020-06-18 11:39:14,266] {logging_mixin.py:112} INFO - Saving raw...
[2020-06-18 11:39:14,269] {taskinstance.py:1145} ERROR - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/isaias/anaconda3/envs/cmpc/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/isaias/airflow/dags/extract_SH_macerado.py", line 125, in save_raw
    for filepath in filepaths:
TypeError: 'NoneType' object is not iterable
[2020-06-18 11:39:14,271] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-18 11:39:23,658] {logging_mixin.py:112} INFO - [2020-06-18 11:39:23,658] {local_task_job.py:103} INFO - Task exited with return code 1
